name: Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  main:
    name: Build and push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: igeolise/traveltime-k6-benchmarks
          tags: |
            type=raw,value=latest
            type=sha,prefix=

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

